settings:
  rootPath: "./deploy"
  config:
    disableFlannel: false
    disableServiceLB: true
    disableTraefik: true
    disableLocalPath: true
    startupTimeout: 2m
  cluster:
    master:
      - node1
  haIP: "192.168.122.62"

charts:
  ingress-nginx:
    version: 4.7.0
    namespace: network 
    timeout: 2m
    releaseName: ingress-nginx
  metallb:
    version: 0.13.9
    releaseName: metallb
    namespace: network
    timeout: 2m
  longhorn:
    version: 1.4.2
    releaseName: longhorn
    namespace: network 

packages:
  k3s: 
    path: pkgs/k3s/k3s
    type: file
  installsh:
    path: pkgs/k3s/install.sh
    type: file
  helm:
    path: pkgs/helm/helm
    type: file
  k3s-selinux:
    path: pkgs/k3s-selinux
    type: rpm

images:
  k3s-airgap:
    path: images/k3s-airgap-images-amd64.tar.gz
  nginx-ingress:
    path: images/nginx-ingress-v1.8.0.tar
  metallb:
    path: images/metallb-v0.13.9.tar
  longhorn:
    path: images/longhorn-1.4.2.tar

nodes:
  node1:
    address: 192.168.122.62
    rootPassword: "endqMjAyMw=="
    requirements:
      cpu: 2
      memory: 4Gi
      storage: 50Gi
      kernelVersion: "5.4"
    installPackages:
      - k3s
      - installsh
      - k3s-selinux
      - helm
    preloadImages:
      - k3s-airgap
      - nginx-ingress
      - metallb

steps:
  # - type: k3s
  - type: chart
    charts:
      - metallb
      - ingress-nginx
      